---
name: release
on:
  push:
    branches:
      - develop

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: build changelog
        uses: mikepenz/release-changelog-builder-action@v4.1.0
        with:
          commitMode: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
